### ISSUE TITLE
Have all the issues disappeared? or is it just me?

### ISSUE THREAD

**Issue by sbridger** [TurboPack/AsyncPro#2]

**Comment by romankassebaum** [comment]
With your last review you added a named branch to the repo. This branch broke the HG compatibility so that I had to recreate the whole project. Thereby I lost the issues.

**Comment by sbridger** [comment]
Sorry about that. I was following the Github howto, so I am a bit lost as to what to do.

Can you create a workflow for contributors that would prevent this happening, and be just how you would like it to be? What do you want me to do? (I don't have "a way" of my own, so I'm happy to do it your way)

Would I be better just keeping my own project and you just do manual merges?

I recall that sourceforge has an import from github feature now. If GH is fragile, should we be trying to back it up to git on SF, so there is a copy somewhere.

I know you have closed discussion here as off topic. Is there a forum for discussion that you use?

Bigger issue:
There doesn't seem to be any single place where a new user could start and get:
Documentation
Instructions that work
full source

Do you have thoughts on where this should be?
Should I try to pull a documentation package together for GH, or should it go onto SF with forums, wiki etc, and just make sure that the sourcecode and bug tracker is on GH?

**Comment by romankassebaum** [comment]
The problem is that I'm working with hg and not with git. I'm using the TortoiseHG tool for all my repos.
Normally I would prefer bitbucket with hg instead of github and git but Marco asked me to use github.

TortoiseHG allows to work with git repos but this has some limitations. One limitation seems to be a named branches. But you can use normal patches, they are working fine.

I think you can put all discussions, documentations etc. here at github. I thought that I only closed issues but maybe I did something wrong.
